server:
  port: 7000
  shutdown: graceful

logging:
  level:
    org.springframework: ERROR
    com.github.leandrochp.passwordvalidatorservice: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log

spring:
  jackson:
    time-zone: Brazil/East
    locale: pt-BR
    default-property-inclusion: non-null
