server:
  port: 7000
  shutdown: graceful

logging:
  level:
    org.springframework: ERROR
    com.github.leandrochp.passwordvalidatorservice: DEBUG
  pattern:
    console: "[%d{dd-MM-yyyy HH:mm:ss.SSS}] - %msg%n"
    file: "[%d{dd-MM-yyyy HH:mm:ss.SSS}] [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: app.log

spring:
  jackson:
    time-zone: Brazil/East
    locale: pt-BR
    default-property-inclusion: non-null
